package Chatr.Server;

import Chatr.Converstation.Message;
import Chatr.Helper.CONFIG;
import Chatr.Helper.JSONTransformer;

import java.util.ArrayList;
import java.util.List;

/**
 * server side message logic
 */
public class MessageHandler {
	private L1Cache l1Cache;
	private List<Request> requests;
	private List<String> answer = new ArrayList<>();

	/**
	 * Instantiates the MessageHandler
	 * @param request request from the client
	 */
	protected MessageHandler(List<String> request) {
		this.l1Cache = Initializer.l1Cache;
		requests = parseRequests(request);
	}

	/**
	 * parses the requests and stores them for further processing
	 * @param requests requests from the Client
	 * @return parsed List of all the requests to the server by the client
	 */
	private List<Request> parseRequests(List<String> requests) {
		List<Request> parsed = new ArrayList<>();
		for (String request : requests) {
			String[] partials = request.split(CONFIG.SEPARATOR);
			Request req = new Request(partials[0], partials[1], partials[2]);
			parsed.add(req);
		}
		return parsed;
	}

	/**
	 * Directs requests to the corresponding methods
	 */
	public void processRequests() {
		for (Request request : requests) {
			switch (request.getRequestType()) {
				case CREATE:
					create(request);
					break;
				case READ:
					read(request);
					break;
				case UPDATE:
					update(request);
					break;
				case DELETE:
					delete(request);
					break;
			}
		}
	}

	/**
	 * stores Message in the Cache
	 * @param request Message wrapped in a request
	 */
	private void create(Request request) {
		Message m = request.getMessage();
		l1Cache.put(request.getConversationID(), m.getTime(), m);
	}

	/**
	 * Gets the newer Messages from the Cache
	 * @param request Message wrapped in a request
	 */
	@SuppressWarnings("Unchecked")
	private void read(Request request) {
		Message m = request.getMessage();
		long timestamp = (m.isEmpty()) ? 0L : m.getTime();
		try {
			List<Message> newer = l1Cache.getNewer(request.getConversationID(), timestamp);
			if (!newer.isEmpty()) {
//				l1Cache.print();
//				System.out.println("newer = " + newer);
				answer.addAll(JSONTransformer.toJSON(newer));
			}
		} catch (Exception e) {
		}
	}

	/**
	 * Updates a request in the Cache
	 * @param request Message wrapped in a request
	 */
	private void update(Request request) {

	}

	/**
	 * Deletes a Message from the Cache
	 * @param request Message wrapped in a request
	 */
	private void delete(Request request) {

	}

	/**
	 * Returns a list of all responses generated by the input requests
	 * @return list of responses generated by the requests
	 */
	public List<String> getResponse() {
		return this.answer;
	}
}
